
const estacoes: TEstacao[] = [
  {
    id: 1,
    nome: 'Eldorado',
    desc: 'Rua Jequitibás, 530 - Eldorado',
    info: 'Estação 1',
    entorno: [
      'Estação de Integração de Ônibus Metropolitanos',
      'Itaú Power Shopping',
      'Big Shopping',
    ],
  },
  {
    id: 2,
    nome: 'Cidade Industrial',
    desc: 'Rua Cláudia Neves, 85 - Camargos',
    info: 'Tranquila',
    entorno: [
      'Itaú Power Center',
    ],
  },
  {
    id: 3,
    nome: 'Vila Oeste',
    desc: 'Rua Maria José Assumpção, 61 - Vila Oeste',
    info: 'Bagunça',
    entorno: [
      'CEFET/MG (Campus 2)',
      'DETRAN',
      'Igreja João XXIII',
      'Igreja Batista da Vila Oeste',
      'Igreja Pentecostal Deus é Amor',
    ],
  },
  {
    id: 4,
    nome: 'Gameleira',
    desc: 'Rua Craveiro Lopes, 617 - Gameleira',
    info: 'Puc Minas Expominas',
    entorno: [
      'Hospital Sarah Kubistchek',
      'Hospital Galba Veloso',
      'Fundação Ezequiel Dias',
      '5º Batalhão da Polícia Militar',
      'Centro de Formação Profissional Paulo de Tarso (SENAI)',
    ],
  },
  {
    id: 5,
    nome: 'Calafate',
    desc: 'Rua Guaratã, 1.052 – Calafate',
    info: 'Nenhum',
    entorno: [
      'Hospital Infantil Santa Terezinha',
      'PAM Padre Eustáquio',
      'Complexo da Polícia Militar',
      'Igreja de São José do Calafate',
      'Igreja de Jesus Cristo dos Santos dos Últimos Dias',
      'Centro de Integração e Apoio ao Portador de Deficiência Rogéria Amato (SESI)',
    ],
  },
  {
    id: 6,
    nome: 'Carlos Prates',
    desc: 'Av. Nossa Senhora de Fátima, 2.875 - Carlos Prates',
    info: 'Nenhum',
    entorno: [
      'Hospital Felício Rocho',
      'Hospital Frederico Ozanam',
      'Hospital Vera Cruz',
      'Hospital Socor',
      'Maternidade Odete Valadares',
      'Instituto São Rafael',
      'Escola de Saúde de Minas Gerais',
      'Centro de Saúde Oswaldo Cruz',
      'Fórum Lafayette',
      'Instituto de Identificação (SSPMG)',
      '12º Batalhão de Infantaria do Exército',
      'Complexo da Polícia Militar',
      'Cemitério do Bonfim',
      'Faculdade Estácio de Sá (Campus Prado)',
      'Igreja Batista do Barro Preto',
      'Igreja de São Sebastião',
    ],
  },
  {
    id: 7,
    nome: 'Lagoinha',
    desc: 'Av. do Contorno, 11.671, Centro',
    info: 'Nenhum',
    entorno: [
      'Terminal Rodoviário',
      'Restaurante Popular',
      'Shopping Oiapoque',
      'Shopping Tupinambás',
      'Shopping Cidade ',
      'Mercado Municipal',
      'Minascentro',
      'UAI - Praça Sete',
      'SESC',
      'SENAC',
      'SENAI – Centro de Formação Prof. Américo René Giannetti',
      'UNI-BH',
      'FACISA',
      'FABRAI ',
      'Colégio/Faculdade Batista de Minas Gerais',
      'Hospital Municipal Odilon Behrens',
      'Departamento de Investigações da Polícia Civil',
      'Conjunto IAPI',
      'Igreja de Nossa Senhora da Conceição',
      'Igreja de São Cristóvão',
      'Igreja Batista da Floresta',
      'Igreja Batista da Lagoinha',
      'Igreja do Evangelho Quadrangular ',
      'Administração Regional Noroeste da PBH',
    ],
  },
  {
    id: 8,
    nome: 'Central',
    desc: 'Praça Rui Barbosa, s/nº - Centro',
    info: 'Centro de BH',
    entorno: [
      'Estação Ferroviária',
      'Estação BHBUS Aarão Reis ',
      'Parque Municipal Américo Renné Gianetti',
      'Museu de Artes e Ofícios Shopping Cidade',
      'Mercado Municipal ',
      'UAI - Praça Sete',
      'Minascentro',
      'Serraria Souza Pinto',
      'Fundação Municipal de Cultura',
      'DER/MG',
      'IPHAN (Casa do Conde de Santa Marina)',
      'JUCEMG Prefeitura de Belo Horizonte',
      'Ministério da Fazenda',
      'Agência Central dos Correios',
      'Palácio das Artes',
      'Teatro Francisco Nunes',
      'Centro Cultural da UFMG',
      'Faculdade de Direito da UFMG',
      'Instituto de Educação',
      'Faculdade Estácio de Sá',
      'Colégio e Faculdade Batista de Minas Gerais',
      'Faculdade São Camilo Faculdade de Ciências Médicas de Minas Gerais',
      'Hospital do IPSEMG',
      'Teatro e TV Alterosa',
      'Record',
      'Igreja São José',
      'Igreja de Nossa Senhora das Dores',
      'Igreja São Pedro Apóstolo',
      'Igreja do Evangelho Quadrangular',
      'Igreja Pentecostal Deus é Amor',
      'Igreja Internacional da Graça de Deus',
      'Igreja Metodista Central',
      'Administração Regional Centro-Sul da PBH',
      'Biblioteca pública',
    ],
  },
]

export { estacoes };